---
- name: Copy backend deployment
  template:
    src: "backend/artifact.tar.gz"
    dest: "~/prod/artifact.tar.gz"

- name: extract backend deployment
  shell: |
    cd ~/prod/
    tar -xvzf artifact.tar.gz
    rm artifact.tar.gz
    
- name: Executing node using pm2
  shell: |
    cd ~/prod/
    npm install
    pm2 stop default
    pm2 start npm -- start