---
- name: Copy backend deployment
  become: true
  template:
    src: "files/artifact.tar.gz"
    dest: "~/prod/artifact.tar.gz"

- name: extract backend deployment
  become: true
  shell: |
    cd ~/prod/
    tar -xvzf artifact.tar.gz
    rm artifact.tar.gz

- name: Executing node using pm2
  become: true
  shell: |
    cd ~/prod/
    npm install
    pm2 stop default
    pm2 start npm -- start