---
- name: Copy backend deployment
  become: true
  copy:
    src: "files/artifact.tar.gz"
    dest: "/srv/artifact.tar.gz"

- name: extract backend deployment
  become: true
  shell: |
    cd /srv/
    tar -xvzf artifact.tar.gz
    rm artifact.tar.gz

- name: Executing node using pm2
  shell: |
    cd /srv/
    npm install
    pm2 stop default
    pm2 start npm -- start